### ISSUE TITLE
Software version and firmware version display on LCD

### ISSUE THREAD

**Issue by TNarakol-UEC** [Ulnooweg/GroBot#11]
Add ability to check software version on LCD display to easily check if it needs updating. Also add a separate menu to display the firmware version.

**Comment by TNarakol-UEC** [comment]
@SeyitTumturk-UEC  I'm removing myself from this assignment now as it's only the LCD part remaining.

**Comment by TNarakol-UEC** [comment]
@SeyitTumturk-UEC  sorry I changed how the structure work. The software version number is now the file "softver" in /code. This is accessible thru readcsv_softver() defined in config.py and returns a list that can be accessed as list[row][columns].

Don't use normal readcsv or writecsv for software version. Right now that is reserved for firmware changes only.

**Comment by TNarakol-UEC** [comment]
@SeyitTumturk-UEC all of these are preferably in a new submenu called system info. With separate buttons to display current software version and current firmware version

**Comment by SeyitTumturk-UEC** [comment]
Added under system_info() - in main menu.
