### ISSUE TITLE
Pressing "stop watering now" shows, sometimes stuck on, watering transition screen

### ISSUE THREAD

**Issue by TNarakol-UEC** [Ulnooweg/GroBot#2]
https://github.com/user-attachments/assets/c7939c3b-8473-4dec-b804-d2ef64ad5cf3

As seen, after turning on the pump manually. Sometimes after pressing "stop watering now" the screen transition to "watering" status screen briefly (one time it is stuck there until another button is pressed and it goes to normal) which is not intended. Watering should show only when it is watering.

**Comment by TNarakol-UEC** [comment]
See also this video

https://github.com/user-attachments/assets/63637a07-49c8-47af-97b8-16e6463662b0

**Comment by SeyitTumturk-UEC** [comment]
Tested and passed.
