### ISSUE TITLE
Soil Moisture Threshold menu adds an extra percent sign when scrolling from a 2 digit percentage to a 1 digit percentage.

### ISSUE THREAD

**Issue by c-seymour-UEC** [Ulnooweg/GroBot#23]
scrolling from 10% to 9% results in the text reading "9%%"
![Media (9)](https://github.com/user-attachments/assets/944adbf6-33d1-4ef2-bc39-60705048afd8)
![Media (10)](https://github.com/user-attachments/assets/724d94f1-a09e-47f9-93e9-f6cd643553be)

**Comment by SeyitTumturk-UEC** [comment]
Will allocate time next sprint to clear all LCD related bugs. Wela'lin for detailed bug reports.

**Comment by SeyitTumturk-UEC** [comment]
Fixed
