### ISSUE TITLE
MOSFET reset not running properly as it is not called in BoardMOSFETreset.py

### ISSUE THREAD

**Issue by TNarakol-UEC** [Ulnooweg/GroBot#24]
grobotboot() function was not called in the BoardMOSFETreset.py after its functionality was moved to grobotboot() function as to be callable by main so it is not doing anything on boot.

**Comment by TNarakol-UEC** [comment]
Add a call to grobotboot() after function definition

**Comment by TNarakol-UEC** [comment]
Fixed confirmed working on test unit. Will push with 1.0.4

**Comment by Ulnooweg-Education-Centre-Engineering** [comment]
Not needed, grobot main already ran the mosfet close code with highest priority. (1st line after all imports)
