### ISSUE TITLE
Add an option to write log to file immediately

### ISSUE THREAD

**Issue by TNarakol-UEC** [Ulnooweg/GroBot#31]
**Details**
A new function logtofile() is defined in logoutput.py. Needs to integrate it with lcddisplay so there's a button to write logfile immediately for bug fixing.

**Comment by Seyitumturk** [comment]
Is " immediately" a priority or feature ?

**Comment by TNarakol-UEC** [comment]
immediately as in on selecting

**Comment by TNarakol-UEC** [comment]
All of these has the same priority unless labelled CRITICAL

**Comment by TNarakol-UEC** [comment]
@SeyitTumturk-UEC  This should be a button called "Log Export" under the new system info submenu

**Comment by SeyitTumturk-UEC** [comment]
Done and tested
