### ISSUE TITLE
Pressing "stop watering now" turns text weird

### ISSUE THREAD

**Issue by TNarakol-UEC** [Ulnooweg/GroBot#4]
This might be hardware but it only happened to me on pressing "stop watering now" twice now. Requiring machine hard reset.

https://github.com/user-attachments/assets/95610c6a-618e-4372-9062-779c77d2a38d

**Comment by SeyitTumturk-UEC** [comment]
I dove into it - with the alien chars its likely the Concurrency issues: The LCD is managed in a separate thread (lcd_menu_thread) from the main thread where the watering control is handled. If there are synchronization issues or race conditions between these threads, it could lead to unexpected behavior like the LCD text becoming garbled.  Currently worked for tests I did on my end.
